### ISSUE TITLE
Issue with printing paged data frames using the html_clean format

### ISSUE THREAD

**Issue by megaraptor1** [juba/rmdformats#98]
I've been noticing an issue with the html_clean rmdformat. I've been trying to print some data frames as part of an html document, but what ends up happening is that the printed data.frame end up located in a small inset window that doesn't take up the entire width of the document. Additionally the columns are very compressed, resulting in the column names being cut off or being omitted in the case of very short columns such as columns reporting N.

I have been trying to figure out what command is producing this result, but have been unable to figure it out. I tried adjusting the output commands `thumbnails`, `gallery`, and `lightbox`, but none of these appear to affect the printed data frame.

Here is a replicable example using the `mtcars` dataset. Also attached is an example jpeg using this dataset to show the results I get.

---
output:
  rmdformats::html_clean:
    highlight: haddock
    number_sections: TRUE
    code_folding: show
    df_print: paged
---
```{r}
data(mtcars)
mtcars
![example](https://user-images.githubusercontent.com/74024763/111570169-96299700-877a-11eb-9e63-a134b6a6c74a.jpg)
```

I tried getting around this by printing the data frames as a kable, but this ended up not working because I had so many columns they ended up extending behind the table of contents. I am trying to print the data as a paged table but unfortunately kable does not allow this.

Notably, I did some testing and found out this is something that happens only with the html_clean rmdformat. When I try to knit the document using the base html_document style it outputs the table correctly, showing all of the columns at the correct width and having the table extend across the entire width of the document. I also tried running the data using the robobook style, and it also produced the data in a form that is readable, though there is still an issue where the with of the column is set to the number of digits which ends up in the numbers being wrapped over multiple rows.

**Comment by juba** [comment]
I just pushed a small fix. Can you confirm it fixes the width issue for you ?

**Comment by megaraptor1** [comment]
I re-ran the code and it doesn't seem to have fixed the issue. I am not sure how to update the rmdformats code. I tried install.packages("rmdformats") and it did not fix the issue.

**Comment by juba** [comment]
The fix is only available in the development version, which you can install with : 

```
remotes::install_github("juba/rmdformats")
```

Using `install.packages` only reinstall the published on CRAN, which is only updated once in a while.

**Comment by megaraptor1** [comment]
Just downloaded the new version from github. The table width issue is fixed, but the names of the columns are still being cut off.
![html_clean example](https://user-images.githubusercontent.com/74024763/111826650-54563900-88bf-11eb-8080-9e630491cd7c.jpg)

**Comment by juba** [comment]
Yes, you're right, there was a padding issue. Could you test again with the latest development version when you find the time to do it ?

**Comment by megaraptor1** [comment]
It works now. Everything seems to be working fine.
